### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by noslowd0wn** [stonar96/RayTraceAntiXray#23] opened 2024-05-05 00:36 UTC
Add suport for plugin orebfuscator, because engine mod in paper can obfuscate blocks only to stone -_-, mod 2 can use only blocks from config and engine mod 3 the same, and i wont that blocks will be replaced with blocks are which are nearby becouse it's much more better to prepair gameplay for cheaters

**Comment by noslowd0wn** [comment] 2024-05-05 00:40
For exmple this is without antixray
![photo_5310101465613853004_y](https://github.com/PaperMC/Paper/assets/65243837/5b29c773-493e-4087-94ec-c566bb0cf8a1)
![photo_5310101465613853007_y](https://github.com/PaperMC/Paper/assets/65243837/8d68aca0-a982-4054-b7e3-05d3971ad2be)

This is paper angine mod 1
![photo_5310101465613853005_y](https://github.com/PaperMC/Paper/assets/65243837/12f0607a-da2a-41d6-ad84-8f50f83b8252)
![photo_5310101465613853008_y](https://github.com/PaperMC/Paper/assets/65243837/10eaca7b-a199-4e71-8f5b-0992803d83d8)

This is my engine mod 4
![photo_5310101465613853006_y](https://github.com/PaperMC/Paper/assets/65243837/aa1d989a-60c6-4fb2-9a3e-acc10eb90c77)
![photo_5310101465613853009_y](https://github.com/PaperMC/Paper/assets/65243837/332ce8c1-2aa8-428e-ab88-f05569fe8a25)

**Comment by stonar96** [comment] 2024-05-05 12:13
> Add suport for plugin orebfuscator

This is not how this works. This would require modifying how Orebfuscator works. For the built-in Paper Anti-Xray I'm doing this by basically replacing parts of the server's internal Anti-Xray implementation by the plugin's one. Also note that Orebfuscator also has a ray tracing feature. However, it works quite a bit different, less accurate and less efficient (hence RayTraceAntiXray, which uses Paper Anti-Xray, which also does the block replacements in a more efficient way to begin with).

> paper can obfuscate blocks only to stone

That's not quite true. `engine-mode: 1` replaces specified blocks (`hidden-blocks`) with other "fake" blocks, `stone` (`deepslate` at y < 0), `netherrack`, or `end_stone` based on the dimension. (See [Paper docs](https://docs.papermc.io/paper/anti-xray).) Hiding ores is the primary scope of Paper Anti-Xray and this plugin.

> i wont that blocks will be replaced with blocks are which are nearby

Duplicate of #2. Read my comment in this issue. As you can see, I've even implemented custom block replacement for testing purposes. However, this is at the expense of efficiency (the Paper Anti-Xray obfuscation algorithm is highly optimized, custom block replacement is not envisaged) and config backward compatibility.

**Closed by stonar96** 2024-05-05 12:13 UTC
